# Generated by Django 2.0.4 on 2018-04-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputat',
            name='vrd_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deputat',
            name='vrd_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
